Watching for file changes with StatReloader
Performing system checks...

2024-12-14 23:48:34.130471: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-14 23:48:34.130661: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-14 23:48:35.749592: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-14 23:48:35.749645: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-14 23:48:35.749677: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-14 23:48:35.750029: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 14, 2024 - 23:48:35
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[14/Dec/2024 23:48:37] "GET /faceforensics/ HTTP/1.0" 200 2949
[14/Dec/2024 23:48:39] "GET /model_types/ HTTP/1.0" 200 4854
[14/Dec/2024 23:48:41] "GET /faceforensics/ HTTP/1.0" 200 2949
[14/Dec/2024 23:48:42] "GET /model_types/ HTTP/1.0" 200 4854
[14/Dec/2024 23:49:25] "GET /model_types/ HTTP/1.0" 200 4887
[14/Dec/2024 23:50:04] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:11:10] "GET /model_use/ HTTP/1.0" 200 3431
/myproject/myproject/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 00:12:07.275750: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 00:12:07.275804: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 00:12:08.834194: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 00:12:08.834246: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 00:12:08.834278: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 00:12:08.834615: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 00:12:09
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Not Found: /hudson
[15/Dec/2024 00:21:50] "GET /hudson HTTP/1.0" 404 2885
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 00:22:54.192769: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 00:22:54.192822: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 00:22:55.756610: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 00:22:55.756662: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 00:22:55.756695: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 00:22:55.757074: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 00:22:55
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 00:23:14] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 00:23:20] "POST /process_video/ HTTP/1.0" 200 3645
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 00:26:35.887624: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 00:26:35.887682: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 00:26:37.486725: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 00:26:37.486817: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 00:26:37.486854: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 00:26:37.487330: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 00:26:37
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 00:28:29] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 00:28:34] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:28:36] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 00:28:46] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:31:25] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:31:27] "GET /model_comparison/ HTTP/1.0" 200 778
[15/Dec/2024 00:31:28] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 00:31:31] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 00:31:34] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 00:31:37] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:31:39] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 00:31:41] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:31:49] "GET /model_comparison/ HTTP/1.0" 200 778
[15/Dec/2024 00:31:51] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 00:31:53] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 00:31:58] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 00:31:59] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 00:32:01] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 00:32:02] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 00:41:30] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 00:41:40] "POST /process_video/ HTTP/1.0" 200 3651
[15/Dec/2024 00:42:10] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 00:42:12] "GET /model_comparison/ HTTP/1.0" 200 778
[15/Dec/2024 00:42:13] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 00:42:14] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:42:15] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 00:42:16] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:42:27] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 00:42:31] "GET /model_comparison/ HTTP/1.0" 200 778
[15/Dec/2024 00:42:33] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 00:42:36] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 00:42:41] "GET /model_comparison/ HTTP/1.0" 200 778
[15/Dec/2024 00:42:42] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 00:43:12] "GET /model_use/ HTTP/1.0" 200 3441
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 01:14:46.334398: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:14:46.334470: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 01:14:48.313144: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:14:48.313440: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 01:14:48.313624: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 01:14:48.314057: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 01:14:48
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 01:17:39.684840: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:17:39.685008: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 01:17:41.265034: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:17:41.265309: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 01:17:41.265499: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 01:17:41.265851: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 01:17:41
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 01:19:23.803151: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:19:23.803204: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 01:19:25.437978: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:19:25.438031: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 01:19:25.438067: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 01:19:25.438389: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 01:19:25
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 01:20:02.619540: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:20:02.619595: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 01:20:04.238040: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:20:04.238241: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 01:20:04.238342: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 01:20:04.238734: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 01:20:04
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 01:21:46] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 01:21:50] "POST /process_video/ HTTP/1.0" 200 3977
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 01:22:26.328207: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:22:26.328263: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 01:22:27.974384: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:22:27.974543: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 01:22:27.974621: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 01:22:27.975040: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
ImportError: cannot import name 'process_video' from 'myproject.views' (/myproject/myproject/views.py)
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 01:22:31.997610: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:22:31.997797: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 01:22:33.619449: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:22:33.619505: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 01:22:33.619538: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 01:22:33.619870: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 01:22:33
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 01:22:51.212676: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:22:51.212734: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 01:22:52.836074: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 01:22:52.836138: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 01:22:52.836181: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 01:22:52.836513: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 01:22:53
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 01:47:03] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 01:48:12] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 02:02:26] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 02:20:26] "GET / HTTP/1.0" 200 2342
[15/Dec/2024 02:20:28] "GET /model_types/ HTTP/1.0" 200 4713
[15/Dec/2024 02:32:44] "GET /model_types/ HTTP/1.0" 200 4784
[15/Dec/2024 02:35:26] "GET /model_types/ HTTP/1.0" 200 5200
[15/Dec/2024 02:41:33] "GET /model_types/ HTTP/1.0" 200 5104
[15/Dec/2024 02:42:05] "GET /model_types/ HTTP/1.0" 200 5104
[15/Dec/2024 02:42:08] "GET / HTTP/1.0" 200 2337
[15/Dec/2024 02:42:09] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 02:42:11] "GET /model_types/ HTTP/1.0" 200 5104
[15/Dec/2024 02:42:17] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 02:42:47] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 02:42:48] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 02:42:54] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 02:42:57] "GET /model_comparison/ HTTP/1.0" 200 778
[15/Dec/2024 02:42:59] "GET /model_use/ HTTP/1.0" 200 3441
[15/Dec/2024 02:43:02] "GET /model_types/ HTTP/1.0" 200 5104
[15/Dec/2024 02:43:28] "GET /model_types/ HTTP/1.0" 200 5099
[15/Dec/2024 02:44:01] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 02:44:04] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 02:44:20] "GET /faceforensics/ HTTP/1.0" 200 2949
[15/Dec/2024 02:44:22] "GET /model_types/ HTTP/1.0" 200 5099
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 02:44:39.771874: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:44:39.772052: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 02:44:41.777263: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:44:41.777632: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 02:44:41.777803: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 02:44:41.778543: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 02:44:42
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 02:44:46] "GET /model_types/ HTTP/1.0" 200 5099
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 02:48:25.718896: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:48:25.719146: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 02:48:27.332788: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:48:27.332872: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 02:48:27.332910: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 02:48:27.333253: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 02:48:27
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 02:49:56.287219: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:49:56.287402: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 02:49:57.918581: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:49:57.918651: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 02:49:57.918688: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 02:49:57.919421: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 60, in <module>
    from .utils import process_video_with_colab  # Colab 통신 함수 임포트
ModuleNotFoundError: No module named 'myproject.utils'
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 8, in <module>
    from .utils import process_video_with_colab  # Colab 통신 함수 임포트
ModuleNotFoundError: No module named 'myproject.utils'
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 8, in <module>
    from .utils import process_video_with_colab  # Colab 통신 함수 임포트
ModuleNotFoundError: No module named 'myproject.utils'
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 02:54:56.701067: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:54:56.701131: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 02:54:58.375465: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 02:54:58.375538: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 02:54:58.375578: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 02:54:58.375931: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 02:54:58
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 03:00:03] "GET / HTTP/1.1" 200 2347
[15/Dec/2024 03:00:05] "GET /model_use/ HTTP/1.1" 200 3436
[15/Dec/2024 03:00:05] "GET /static/css/base.css HTTP/1.1" 304 0
[15/Dec/2024 03:01:16] "GET /model_types/ HTTP/1.0" 200 5094
[15/Dec/2024 03:01:25] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 03:01:57] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:02:01] "GET /model_use/ HTTP/1.0" 200 3436
[15/Dec/2024 03:02:03] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:02:04] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 03:02:05] "GET /model_types/ HTTP/1.0" 200 5094
[15/Dec/2024 03:04:12] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:04:12] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:04:15] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:04:19] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:04:28] "GET /model_use/ HTTP/1.0" 200 3436
[15/Dec/2024 03:04:59] "POST /process_video/ HTTP/1.0" 200 3972
[15/Dec/2024 03:05:08] "GET /model_use/ HTTP/1.0" 200 3436
[15/Dec/2024 03:07:17] "GET / HTTP/1.1" 200 2347
Not Found: /favicon.ico
[15/Dec/2024 03:07:18] "GET /favicon.ico HTTP/1.1" 404 2901
[15/Dec/2024 03:07:20] "GET /model_use/ HTTP/1.1" 200 3436
[15/Dec/2024 03:07:21] "GET /static/css/base.css HTTP/1.1" 200 687
[15/Dec/2024 03:07:24] "GET /model_use/ HTTP/1.1" 200 3436
[15/Dec/2024 03:07:24] "GET /model_comparison/ HTTP/1.1" 200 773
[15/Dec/2024 03:07:24] "GET /static/css/model_type.css HTTP/1.1" 200 2326
[15/Dec/2024 03:07:26] "GET /model_types/ HTTP/1.1" 200 5094
[15/Dec/2024 03:07:26] "GET /static/img/origin_server.png HTTP/1.1" 200 6112
[15/Dec/2024 03:07:26] "GET /static/img/current_server.png HTTP/1.1" 200 5094
[15/Dec/2024 03:08:54] "GET /model_types/ HTTP/1.0" 200 5094
[15/Dec/2024 03:21:21] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:21:23] "GET /model_use/ HTTP/1.0" 200 3436
[15/Dec/2024 03:22:55] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:22:57] "GET /model_types/ HTTP/1.0" 200 5094
[15/Dec/2024 03:22:59] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 03:23:00] "GET /model_types/ HTTP/1.0" 200 5094
[15/Dec/2024 03:27:09] "GET / HTTP/1.1" 200 2347
[15/Dec/2024 03:27:11] "GET /model_use/ HTTP/1.1" 200 3436
[15/Dec/2024 03:27:21] "GET /model_use/ HTTP/1.1" 200 3436
[15/Dec/2024 03:27:43] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:29:37] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:30:20] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 03:34:55] "GET /model_types/ HTTP/1.1" 200 5094
[15/Dec/2024 03:34:55] "GET /static/img/origin_server.png HTTP/1.1" 200 6112
[15/Dec/2024 03:34:55] "GET /static/css/model_type.css HTTP/1.1" 200 2326
[15/Dec/2024 03:34:55] "GET /static/img/current_server.png HTTP/1.1" 200 5094
[15/Dec/2024 03:35:48] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 03:35:49] "GET /faceforensics/ HTTP/1.0" 200 2939
[15/Dec/2024 03:35:50] "GET /model_types/ HTTP/1.0" 200 5094
[15/Dec/2024 03:44:47] "GET /model_types/ HTTP/1.0" 200 5030
Not Found: /portal/redlion
[15/Dec/2024 03:51:05] "GET /portal/redlion HTTP/1.0" 404 2909
[15/Dec/2024 04:00:11] "GET / HTTP/1.1" 200 2347
[15/Dec/2024 04:00:12] "GET /model_use/ HTTP/1.1" 200 3436
[15/Dec/2024 04:01:12] "GET / HTTP/1.1" 200 2347
[15/Dec/2024 04:01:14] "GET /model_use/ HTTP/1.1" 200 3436
[15/Dec/2024 04:01:26] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 04:01:29] "GET /model_use/ HTTP/1.0" 200 3436
[15/Dec/2024 04:04:05] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.0" 200 2347
